#!/bin/zsh
set -x
# Script to compile a gemc tag and install it inside a bin/$OSRELEASE subdir of source
#
# Warning: must be run at the top dir location where the tags sub-dir are located
# Make sure the api is present


if [ "$#" -ne 1 ]; then
  	echo " "
	echo "Usage:   "
	echo  "  >> $0 <version>"
	echo
	exit 1
fi

TAGTOINSTALL=$1
if [[ ! -d $TAGTOINSTALL ]]; then
	echo $TAGTOINSTALL clas12tag does not exists, exiting
	exit 1
fi

ncpu=$(getconf _NPROCESSORS_ONLN)
# setting max parallel compilation to 20 (check periodically, this was causing problems)
if [ "$ncpu" -ge 20 ]; then
	ncpu=20
fi

echo
echo Installing gemc clas12 tag $TAGTOINSTALL on $OSRELEASE
echo Using $ncpu cpus for the compilation

alias -g opt=' -j'$ncpu' OPT=1'

cd $TAGTOINSTALL/source
scons -c
scons opt
mkdir -p bin/$OSRELEASE

# cp could not work if the executable is in use, but "mv" will work
mv gemc bin/$OSRELEASE
cp bin/$OSRELEASE/gemc ./

