#--------------------------------------------------------------------------
# Analysis Software for Valeri
#
# To buiild:
#
#  docker build -f Dockerfile-Valery -t vpk:1.0 .
#
# To run in batch mode:
#
#  docker run -it --rm vpk bash
#
#  docker tag vpk:0.1 maureeungaro/vpk:0.1
#
#  docker push maureeungaro/vpk:0.1
#
FROM jeffersonlab/clas12tags:4a.2.4
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ENV JLAB_ROOT /jlab
ENV JLAB_VERSION 2.2
ENV CLAS12TAG 4a.2.4

WORKDIR $JLAB_ROOT

# Notice: we need a symbolic link to the mlibrary include as it was missing.
# Should not be needed in 2.3 and up (we also need to fix it there)
# Also notice: the TorusSymmetric.dat field is downloaded manually. It will be downloaded with go_field in the installation

RUN yum install -y python36 python36-devel python36-libs  \
	&& yum install -y swig \
	&& yum install -y gsl-devel gsl root-mathmore  \
	&& yum install -y ncurses-devel ncurses-libs \
	&& yum install -y emacs
